### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by philippr71** [Servoy/svyBase#1]
Strings / Messages should be i18n, please.

**Comment by paronne** [comment]
Hi Roland,

which string/message are you referring specifically ?
There are several errors throwing text msgs. These error msgs aren't meant to be visualized by the user, better to be handled and be nicely reported to the User depending on the use case.

In svyBaseCRUD there are 2 scenario where text is shown in a dialog where text could be internationalized.
However to avoid dependencies issues with th resource project is preferable the svyBase will not have any resource project for the i18n.

```
function confirmDelete(records) {
    var confirmBtn = 'Delete';
    var res = plugins.dialogs.showQuestionDialog('Confirm Delete', 'Do you want to delete the selected record(s)?<br>Note: There is no undo for this operation.', 'Cancel', confirmBtn);
    return (res == confirmBtn);
}
```
In this case, the confirmDelate function can easily be overriden in an extended form  e.g. "omBaseCRUD", there you can have a custom text.

```
function onHideHandler(event) {
    //apply the FormHide policy
    if (getCrudPolicies().getFormHidePolicy() == scopes.svyCRUDManager.FORM_HIDE_POLICY.PREVENT_WHEN_EDITING) {
        if (hasEdits()){
            plugins.dialogs.showInfoDialog('Unsaved Changes', 'Please, save or cancel any unsaved changes before navigating away from the current form.');
            return false;
        }
    }
...
}
```

For the onHideHandler, i see that's harder to override; however ideally the onHideHandler will never return false. That's because the onHide returning false is not well handled in all scenarios (e.g. changing the tab of a tabpanel containing a nested tabpanel).
Using svyBase in conjunction with svyNavigation, when there are pending edits is possible to prevent navigation before the onHide is even fired.

Regards,
Paolo

**Comment by philippr71** [comment]
Solution accepted. These are exactly the two areas that I need to translate.

Regards
Roland
