### ISSUE TITLE
onRecordSelectionHandler does not fire on child forms when no records available

### ISSUE THREAD

**Issue by philippr71** [Servoy/svyBase#2]
There is an issue in the following circumstance:

- master/detail-form-scenario
- you're on a master-record that has some detail-records
- then jump on a master-record that has no detail-records
=> onRecordSelectionHandler and updateUI doesn't fire on the child-form! But these events should also fire here!

This happens in "svyBaseCRUD" on line 1321 and following. In this case the variable "fireHandler" stays null and because of that "applySuper('onRecordSelectionHandler'...)" will not be executed.

**Comment by seanthomasdevlin** [comment]
I'm not sure this can be easily overcome and it doesn't really have much to do with SvyBase. In Servoy forms, there is no event fired when the form changes foundsets and the resulting foundset is empty, as is your case, when the master record is switched. The foundset in the child form is changed to an empty foundset - no selection event is fired in this case. We would need a kind of _onFoundSetChanged_ event, or have record selection events extend to cover empty foundsets.

**Comment by paronne** [comment]
Hi Roland, we looked more deeply into the issue; we could indeed replicate the scenario you describe. The onRecordEventHandler is not propagating the onRecordSelection because there is a "lastSelectedRecord" but not a "selRec".
For a fix you can apply the changes from the commit: https://github.com/Servoy/svyBase/commit/52b7274609698df92740606a0b78adde00c18f60

Regards,
Paolo

**Comment by philippr71** [comment]
Hi Paolo

Thanks, it's exactly the hotfix I've implemented on our side this morning!

Regards,
Roland
